# Site settings
title: Jubiler Złoty Kolczyk
baseurl: ""
url: "https://zlotykolczyk.github.io"

# Build settings
markdown: kramdown
theme: minima
#plugins:
#  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-seo-tag

lang: pl
